version: "3"
services:
    nginx:
        depends_on:
            - arqplatform_client
            - arqplatform_api
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "4200:80"
    arqplatform_client:
        stdin_open: true
        build:
            context: ./arqplatform_client
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./arqplatform_client:/app
    arqplatform_api:
        environment:
            - DB_HOST=host.docker.internal
        build:
            context: ./arqplatform_api
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./arqplatform_api:/app
